version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Replacing table name in the server function"
      - sed -i "s|DYNAMODB_TABLE|$DYNAMODB_TABLE|g" ./src/app.js
      - echo "Adding Swagger host"
      - sed -i "s|<SERVER_ALB_URL>|$SERVER_ALB_URL|g" ./src/swagger/swagger.js
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URL $CODEBUILD_SRC_DIR
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - docker tag $REPO_URL:latest $REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URL:$IMAGE_TAG
      - echo Preparing spec files in new folder
      - cd $CODEBUILD_SRC_DIR_EnvSourceArtifact/backend-deployment/appconfig/
      - mkdir artifacts
      - cp imagedefinition.json artifacts/imagedefinition.json
      - echo Changing directory to the artifacts directory
      - cd artifacts
      - echo Preparating artifacts
      - sed -i "s|<CONTAINER_NAME>|$CONTAINER_NAME|g" imagedefinition.json
      - sed -i "s|<REPO_URL>|$REPO_URL|g" imagedefinition.json
      - sed -i "s|<IMAGE_TAG>|$IMAGE_TAG|g" imagedefinition.json

artifacts:
  files:
    - '**/*'
  base-directory: '$CODEBUILD_SRC_DIR_EnvSourceArtifact/backend-deployment/appconfig/artifacts'
  discard-paths: yes
